### ISSUE TITLE
Load local file

### ISSUE THREAD

**Issue by boblund** [suchipi/webview-node#3]
I'm trying to load a local file using the example:

var child = webview.spawn({
  // options for webview
  title: "My App",
  width: 1024,
  height: 768,
  dir: "./public",
 
  // options for child_process.spawn
  cwd: process.cwd(),
});

"./public" contains index.html. Running the example results in a 404. Changing dir to "./public/index.html also results in a 404. Adding url: "///file/absolutepath/index.html" works.

Is there a way to load a local file other than the "url" property with an absolute path.

Thanks,
Bob

**Comment by boblund** [comment]
After some more experimenting it looks like: 1) dir is ignored, 2) appending a relative path to process.cwd() results in the example loading `$(process.cwd()}/relative_path/index.html`

**Comment by suchipi** [comment]
An error which could have caused this issue (on windows) has been fixed in version 1.1.0.
